// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ0hLLtFUtEqvTH27VwlE025Zccan-iok',
    appId: '1:85416337208:web:d035b6711730a1180f6bcd',
    messagingSenderId: '85416337208',
    projectId: 'periodstracker-c1218',
    authDomain: 'periodstracker-c1218.firebaseapp.com',
    storageBucket: 'periodstracker-c1218.firebasestorage.app',
    measurementId: 'G-CNNT5Q4H4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTfsocL6_yemZkNSNnJb5XlkuNlJ-Vzrc',
    appId: '1:85416337208:android:f88a028a447138fd0f6bcd',
    messagingSenderId: '85416337208',
    projectId: 'periodstracker-c1218',
    storageBucket: 'periodstracker-c1218.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAptLK8iwsLm6bHfNHapvi4Bxfvt_d6T64',
    appId: '1:85416337208:ios:eb56bf942397f1380f6bcd',
    messagingSenderId: '85416337208',
    projectId: 'periodstracker-c1218',
    storageBucket: 'periodstracker-c1218.firebasestorage.app',
    iosBundleId: 'com.example.mensurationTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAptLK8iwsLm6bHfNHapvi4Bxfvt_d6T64',
    appId: '1:85416337208:ios:eb56bf942397f1380f6bcd',
    messagingSenderId: '85416337208',
    projectId: 'periodstracker-c1218',
    storageBucket: 'periodstracker-c1218.firebasestorage.app',
    iosBundleId: 'com.example.mensurationTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ0hLLtFUtEqvTH27VwlE025Zccan-iok',
    appId: '1:85416337208:web:878ccd4284060e640f6bcd',
    messagingSenderId: '85416337208',
    projectId: 'periodstracker-c1218',
    authDomain: 'periodstracker-c1218.firebaseapp.com',
    storageBucket: 'periodstracker-c1218.firebasestorage.app',
    measurementId: 'G-EFZRZ8WSYB',
  );
}
